# !/usr/bin/env python
# -*- coding: utf-8 -*-
machineName = "L18-Y69"
menuNameDict = {
	"MENU_CB_NONE"				: "空菜单",
	"MENU_CB_HOT_10_FKJ_BIG"	: "热杯-10分快浆-高水位",
	"MENU_CB_HOT_10_FKJ_MID"	: "热杯-10分快浆-中水位",
	"MENU_CB_HOT_10_FKJ_SMALL"	: "热杯-10分快浆-低水位",
	"MENU_CB_HOT_SHI_FNT"		: "热杯-十分浓汤",
	"MENU_CB_HOT_YANG_SZ"		: "热杯-养生粥",
	"MENU_CB_HOT_ZI_BH"			: "热杯-滋补糊",
	"MENU_CB_HOT_DUN_Z"			: "热杯-炖煮",
	"MENU_CB_HOT_GUO_RL"		: "热杯-果仁露",
	"MENU_CB_HOT_SHI_HYS"		: "热杯-石斛药膳",
	"MENU_CB_HOT_YIN_EG"		: "热杯-银耳羹",
	"MENU_CB_HOT_YU_MZ"			: "热杯-玉米汁",
	"MENU_CB_HOT_BING_QL"		: "热杯-冰淇淋",
	"MENU_CB_HOT_JING_LT"		: "热杯-精力汤",
	"MENU_CB_HOT_SETTING"		: "热杯-设置",
	"MENU_CB_HOT_RE_HCJ"		: "热杯-热烘除菌",
	"MENU_CB_HOT_SHI_FNJ"		: "热杯-十分浓浆",
	"MENU_CB_HOT_10_FKH_BIG"	: "热杯-10分快糊-高水位",
	"MENU_CB_HOT_10_FKH_MID"	: "热杯-10分快糊-中水位",
	"MENU_CB_HOT_10_FKH_SMALL"	: "热杯-10分快糊-低水位",
	"MENU_CB_HOT_GUO_SZ"		: "热杯-果蔬汁",
	"MENU_CB_HOT_NAI_X"			: "热杯-奶昔",
	"MENU_CB_HOT_QING_X"		: "热杯-清洗",
	"MENU_CB_HOT_DIY_TW"		: "热杯-DIY调温",
	"MENU_CB_HOT_DIY_TS"		: "热杯-DIY调速",

	"MENU_CB_COLD_SHU_LDJ"		:"真空冷杯-熟料豆浆",
	"MENU_CB_COLD_RUAN_GSZ"		:"真空冷杯-软果蔬汁",
	"MENU_CB_COLD_GUO_RL"		:"真空冷杯-果仁露",
	"MENU_CB_COLD_ZHEN_KBX"		:"真空冷杯-真空保鲜",
	"MENU_CB_COLD_GUO_CN"		:"真空冷杯-果菜泥",
	"MENU_CB_COLD_JIANG_L"		:"真空冷杯-酱料",
	"MENU_CB_COLD_BING_QL"		:"真空冷杯-冰淇淋",
	"MENU_CB_COLD_JING_LT"		:"真空冷杯-精力汤",
	"MENU_CB_COLD_SETTING"		:"真空冷杯-设置",
	"MENU_CB_COLD_GUO_SZ"		:"真空冷杯-果蔬汁",
	"MENU_CB_COLD_NAI_X"		:"真空冷杯-奶昔",
	"MENU_CB_COLD_QING_X"		:"真空冷杯-清洗",
	"MENU_CB_COLD_DIY_TS"		:"真空冷杯-DIY调速",

	"MENU_CB_YS_YANG_SC"		:"养生壶-养生茶",
	"MENU_CB_YS_YIN_EG"			:"养生壶-银耳羹",
	"MENU_CB_YS_45DU_CN"		:"养生壶-45度冲奶",
	"MENU_CB_YS_HUA_GC"			:"养生壶-花果茶",
	"MENU_CB_YS_YAO_S"			:"养生壶-药膳",
	"MENU_CB_YS_YAN_W"			:"养生壶-燕窝",
	"MENU_CB_YS_ZHOU_P"			:"养生壶-粥品",
	"MENU_CB_YS_ZI_BH"			:"养生壶-滋补糊",
	"MENU_CB_YS_SETTING"		:"养生壶-设置",
	"MENU_CB_YS_DIY_TW"			:"养生壶-DIY加热",

	"MENU_CB_YM_YAO_SF"			:"研磨杯-药膳粉",
	"MENU_CB_YM_WU_GF"			:"研磨杯-五谷粉",
	"MENU_CB_YM_TIAO_LF"		:"研磨杯-调料粉",
	"MENU_CB_YM_MI_F"			:"研磨杯-米粉",
	"MENU_CB_YM_DOU_F"			:"研磨杯-豆粉",
	"MENU_CB_YM_BING_TF"		:"研磨杯-冰糖粉",
	"MENU_CB_YM_REN_SF"			:"研磨杯-人参粉",
	"MENU_CB_YM_E_J"			:"研磨杯-阿胶粉",
	"MENU_CB_YM_SETTING"		:"研磨杯-设置",
	"MENU_CB_YM_DIY_TS"			:"研磨杯-DIY调速",

	"MENU_CB_DGNB_QIE_S"		:"多功能杯-切丝",
	"MENU_CB_DGNB_JIAO_R"		:"多功能杯-绞肉",
	"MENU_CB_DGNB_HUO_M"		:"多功能杯-和面",
	"MENU_CB_DGNB_QIE_P"		:"多功能杯-切片",
	"MENU_CB_DGNB_JIAO_C"		:"多功能杯-绞菜",
	"MENU_CB_DGNB_SETTING"		:"多功能杯-设置",
	"MENU_CB_DGNB_DIY_TS"		:"多功能杯-DIY调速",
}
workHeadDictH = {
	'OB_NULL'         	: "等待",
	'OB_MOTOR'        	: "搅拌",
	'OB_HEATER'       	: "加热",
	'OB_BUZ'			: "蜂鸣器",
	'OB_REPEAT'			: "重复",
	'OB_H_20S_M_0_1S'	: "每20秒2档搅拌0.1秒",
	'OB_H_30S_M_5S'		: "每20秒1档搅拌3秒",
	'OB_H_60S_M_5S'		: "每60秒1档搅拌5秒",
	'OB_H_120S_M_5S'	: "每120秒1档搅拌5秒",
	'OB_H_CONST_T'		: "恒温加热",
	'OB_MOTO_HEAT_1'	: "搅拌+1档加热",
	'OB_VACUUM'			: "抽真空",
}
workHeadDictL = {
	"END_TIME"					: "时间",
	"END_TEMP"					: "温度",
	"END_TIME_OR_TEMP"			: "时间或温度",
	"END_TIME_AND_TEMP"			: "时间和温度",
	"END_TIME_OR_FY"			: "时间或防溢",
	"END_TIME_OR_TEMP_OR_TEMP_CTRL"	: "时间或温度或突跳器",
	"END_TEMP_OR_FY"			: "温度或防溢",
	"END_TIME_OR_TEMP_OR_FY"	: "时间或温度或防溢",
}
heatRankDict = {
	"HEAT_L1"	:"1",
	"HEAT_L2"	:"2",
	"HEAT_L3"	:"3",
	"HEAT_L4"	:"4",
	"HEAT_L5"	:"5",
	"HEAT_L6"	:"6",
	"HEAT_L7"	:"7",
	"HEAT_L8"	:"8",
	"HEAT_L9"	:"9",
	"HEAT_L10"	:"10",
	
	"MOTO_L1"	: "1",
	"MOTO_L2"	: "2",
	"MOTO_L3"	: "3",
	"MOTO_L4"	: "4",
	"MOTO_L5"	: "5",
	"MOTO_L6"	: "6",
	"MOTO_L7"	: "7",
	"MOTO_L8"	: "8",
	"MOTO_L9"	: "9",
	"MOTO_L10"	: "10",
}
motoRankDict = {

}
