unsigned char code MENU01[][5]= {//浓浆
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,40)		,L10          	    ,60},
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,00)		,L9      	        ,80},
	{OB_Heater|Time_OR_Temp_OR_Fy     	,TIME_x_M_y_S(0,50)		,L9	           		,87},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,10)		,L9      	        ,95},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,20)		,L8      	        ,95},
	{OB_Heater|Time_OR_Fy     			,TIME_x_M_y_S(0,30)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,15)		,L6      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L3},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L6},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L4},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L8},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L5},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L8},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{0,0,0,0,0}		 						                                        
};  
unsigned char code MENU02[][5]= {//浓汤
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,40)		,L10          	    ,60},
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,00)		,L9      	        ,80},
	{OB_Heater|Time_OR_Temp_OR_Fy     	,TIME_x_M_y_S(0,50)		,L9	           		,87},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,10)		,L9      	        ,95},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,20)		,L8      	        ,95},
	{OB_Heater|Time_OR_Fy     			,TIME_x_M_y_S(0,30)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,15)		,L6      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L3},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L6},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L5},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{0,0,0,0,0}	                                                                                    		
};
unsigned char code MENU03[][5]= {//花果茶
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,40)		,L10          	    ,60},
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,00)		,L9      	        ,80},
	{OB_Heater|Time_OR_Temp_OR_Fy     	,TIME_x_M_y_S(0,50)		,L9	           		,87},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,10)		,L9      	        ,95},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,20)		,L8      	        ,95},
	{OB_Heater|Time_OR_Fy     			,TIME_x_M_y_S(0,30)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,15)		,L6      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L6},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L8},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L8},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L8},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{0,0,0,0,0}	 
};
unsigned char code MENU04[][5]= {//滋补糊
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,40)		,L10          	    ,60},
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,00)		,L9      	        ,80},
	{OB_Heater|Time_OR_Temp_OR_Fy     	,TIME_x_M_y_S(0,50)		,L9	           		,87},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,10)		,L9      	        ,95},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,20)		,L8      	        ,95},
	{OB_Heater|Time_OR_Fy     			,TIME_x_M_y_S(0,30)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,10)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L3},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L6},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L4},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,5)		,L2      	        ,100},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L8},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{0,0,0,0,0}	 	
};
unsigned char code MENU05[][5]= {//养生粥
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,35)		,L10          	    ,60},
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,00)		,L9      	        ,80},
	{OB_Heater|Time_OR_Temp_OR_Fy     	,TIME_x_M_y_S(0,50)		,L9	           		,87},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,10)		,L9      	        ,95},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,20)		,L8      	        ,95},
	{OB_Heater|Time_OR_Fy     			,TIME_x_M_y_S(0,30)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,10)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{0,0,0,0,0}	 	
};
unsigned char code MENU06[][5] = {//酱料
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,35)		,L10          	    ,60},
	{OB_M_H_3P20|Time_OR_Temp     		,TIME_x_M_y_S(1,00)		,L9      	        ,80},
	{OB_Heater|Time_OR_Temp_OR_Fy     	,TIME_x_M_y_S(0,50)		,L9	           		,87},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L2},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,10)		,L9      	        ,95},
	{OB_Heater|Time_OR_Temp		     	,TIME_x_M_y_S(0,20)		,L8      	        ,95},
	{OB_Heater|Time_OR_Fy     			,TIME_x_M_y_S(0,30)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L5},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,5)		,MOTOR_MODE 		,L1},
	{OB_Heater|End_Time		     		,TIME_x_M_y_S(0,10)		,L7      	        ,100},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_M_H|End_Time          			,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L7},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,20)		,MOTOR_MODE 		,L3},
	{OB_Motor|End_Time          		,TIME_x_M_y_S(0,30)		,MOTOR_MODE 		,L6},
	{0,0,0,0,0}	
};
unsigned char code MENU07[][5] = {//西洋参粉
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,30)  	,MOTOR_MODE  	,L7},
	{0,0,0,0,0}	
};
unsigned char code MENU08[][5] = {//果蔬汁
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,25) 	,MOTOR_MODE 	,L8},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,35) 	,MOTOR_MODE 	,L2},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,25) 	,MOTOR_MODE 	,L10},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,23) 	,MOTOR_MODE 	,L9},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{0,0,0,0,0}		
};
unsigned char code MENU09[][5]={//奶昔
	{OB_Motor|End_Time				,TIME_x_M_y_S(1,5) 		,MOTOR_MODE 	,L5},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{0,0,0,0,0}																					
};
unsigned char code MENU10[][5]={//冰沙
	{OB_Motor|End_Time				,TIME_x_M_y_S(0,4) 		,MOTOR_MODE 	,L10},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,4)  	,0           	,0},
	{OB_Motor|End_Time				,TIME_x_M_y_S(0,2) 		,MOTOR_MODE 	,L2_0},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,4)  	,0           	,0},
	{OB_Repeat|End_Time        		,TIME_x_M_y_S(0,36)  	,2           	,1 },
	{OB_Motor|End_Time				,TIME_x_M_y_S(0,2) 		,MOTOR_MODE 	,L2_0},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{0,0,0,0,0}																					
};
unsigned char code MENU11[][5]= {//清洗
	{OB_Motor|End_Time  			,TIME_x_M_y_S(0,50)		,MOTOR_MODE		,L10},
	{0,0,0,0,0}		
};