unsigned char code MENU1[][5]= {//浓浆
 	{OB_H_60S_M_5S|Time_OR_Temp   	,TIME_x_M_y_S(20,00)	,HEAT_L1_0_0	,Temp80},
	{OB_H_30S_M_5S|Time_OR_Temp   	,TIME_x_M_y_S(20,00)    ,HEAT_L0_9_0	,Temp87},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,10)   	,0           	,0},
	{OB_Heater|Time_OR_Fy       	,TIME_x_M_y_S(4,0)    	,HEAT_L0_5_0	,0},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)   	,0           	,DISP_UPDATE},
	{OB_Heater|End_Time        		,TIME_x_M_y_S(1,30)		,L2				,0},
	{OB_Heater|End_Time        		,TIME_x_M_y_S(2,00)		,L1				,0},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)   	,0           	,0},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,50)   	,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,20)   	,MOTOR_MODE 	,L3},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,10)   	,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,20)   	,MOTOR_MODE 	,L3},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)   	,0           	,0 },
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,10)   	,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,20)   	,MOTOR_MODE 	,L4},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)   	,0           	,0 },
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,10)   	,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,20)   	,MOTOR_MODE 	,L5},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)   	,0           	,0 },
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,15)   	,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time         		,TIME_x_M_y_S(0,25)   	,MOTOR_MODE 	,L6},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)   	,0           	,0 },
	{OB_Repeat|End_Time        		,TIME_x_M_y_S(13,00)   	,3           	,1 },
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)   	,0           	,0 },
	{OB_H_30S_M_5S|End_Time 		,TIME_x_M_y_S(1,00)		,L1				,0},
	{0,0,0,0,0}		 						                                        
};  
unsigned char code MENU2[][5]= {//浓汤
	{OB_Heater|Time_OR_Temp   		,TIME_x_M_y_S(20,00)	,HEAT_L1_0_0	,Temp75}, 	
	{OB_Heater|Time_OR_Temp   		,TIME_x_M_y_S(20,00)	,HEAT_L0_9_0	,Temp83}, 
	{OB_Heater|Time_OR_Fy  		    ,TIME_x_M_y_S(4,00)		,HEAT_L0_5_0	,0},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)		,0           	,DISP_UPDATE},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,10)		,MOTOR_MODE 	,L3},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Heater|End_Time   		    ,TIME_x_M_y_S(2,00)		,L2				,0},
	{OB_Heater|End_Time   		    ,TIME_x_M_y_S(1,30)		,L1				,0},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,40)		,MOTOR_MODE		,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,30)		,MOTOR_MODE		,L4},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,10)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,10)		,MOTOR_MODE		,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,30)		,MOTOR_MODE		,L5},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,10)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,10)		,MOTOR_MODE		,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,30)		,MOTOR_MODE		,L5},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,10)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,10)		,MOTOR_MODE		,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,30)		,MOTOR_MODE		,L5},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,10)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,10)		,MOTOR_MODE		,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,30)		,MOTOR_MODE		,L5},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L1},
	{OB_Motor|End_Time          	,TIME_x_M_y_S(0,35)		,MOTOR_MODE 	,L7},
	{OB_NULL|End_Time           	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_H_30S_M_5S|End_Time			,TIME_x_M_y_S(1,0)		,L2			    ,0},
	{OB_NULL|End_Time          		,TIME_x_M_y_S(0,10)		,0           	,0},
	{OB_H_60S_M_5S|End_Time			,TIME_x_M_y_S(3,0)		,L1			    ,0},
	{0,0,0,0,0}	                                                                                    		
};
unsigned char code MENU3[][5]= {//花果茶
	{OB_Heater|End_Temp   			,TIME_x_M_y_S(24,0)		,HEAT_L1_0_0	,Temp85},
	{OB_Heater|Time_OR_Fy 			,TIME_x_M_y_S(5,40)		,HEAT_L0_3_0	,0},
	{OB_NULL|End_Time     			,TIME_x_M_y_S(0,20)		,0          	,DISP_UPDATE},
	{OB_Heater|End_Time   			,TIME_x_M_y_S(60,0)		,L1				,0},
	{0,0,0,0,0}	 
};
unsigned char code MENU4[][5]= {//滋补糊
	{OB_H_20S_M_0_1S|Time_OR_Temp   ,TIME_x_M_y_S(20,00)	,HEAT_L0_9_0	,Temp87},
	{OB_H_30S_M_5S|Time_OR_Temp   	,TIME_x_M_y_S(20,00)	,HEAT_L0_8_0	,Temp89},	
	{OB_Heater|Time_OR_Fy      		,TIME_x_M_y_S(5,0)		,HEAT_L0_4_0	,Temp89},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0          	,DISP_UPDATE},
	{OB_H_30S_M_5S|End_Time       	,TIME_x_M_y_S(6,0)		,L1				,Temp89},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(1,0)		,0           	,0},
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,10)		,MOTOR_MODE  	,L1},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,30)		,0           	,0},
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,10)		,MOTOR_MODE  	,L1},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,30)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,30)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L5},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L5},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L5},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L6},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)		,0           	,0}, 
	{OB_Motor|End_Time            	,TIME_x_M_y_S(0,20)		,MOTOR_MODE  	,L5},
	{0,0,0,0,0}	 	
};
unsigned char code MENU5[][5]= {//养生粥
	{OB_H_20S_M_0_1S|Time_OR_Temp   ,TIME_x_M_y_S(20,00)   	,HEAT_L0_9_0	,Temp87},
	{OB_H_30S_M_5S|Time_OR_Temp   	,TIME_x_M_y_S(20,00)    ,HEAT_L0_7_0	,Temp89},
	{OB_Heater|Time_OR_Fy      		,TIME_x_M_y_S(4,30)   	,HEAT_L0_4_0	,Temp89},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,20)   	,0          	,DISP_UPDATE},
	{OB_H_60S_M_5S|End_Time       	,TIME_x_M_y_S(2,0)    	,L1				,Temp89},
	{OB_H_120S_M_5S|End_Time      	,TIME_x_M_y_S(6,0)    	,L1				,Temp89},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(1,0)    	,0          	,0},
	{OB_H_60S_M_5S|End_Time      	,TIME_x_M_y_S(3,0)    	,L1				,Temp89},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(0,30)   	,0          	,0},
	{OB_H_60S_M_5S|End_Time      	,TIME_x_M_y_S(2,30)   	,L1				,Temp89},
	{OB_NULL|End_Time             	,TIME_x_M_y_S(1,0)    	,0          	,0},
	{OB_H_120S_M_5S|End_Time      	,TIME_x_M_y_S(6,0)    	,L1				,Temp89},
	{0,0,0,0,0}	 	
};
unsigned char code MENU6[][5] = {//酱料
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,0) 		,MOTOR_MODE  	,L6},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)      ,0           	,0 },
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,0) 		,MOTOR_MODE  	,L7},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)      ,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,0) 		,MOTOR_MODE  	,L5},
	{OB_NULL|End_Time       		,TIME_x_M_y_S(0,2)     	,0          	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,0) 		,MOTOR_MODE  	,L8},
	{OB_NULL|End_Time       		,TIME_x_M_y_S(0,2)     	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,0) 		,MOTOR_MODE  	,L8},
	{OB_NULL|End_Time       		,TIME_x_M_y_S(0,2)     	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,48)   	,MOTOR_MODE 	,L8},
	{OB_NULL|End_Time       		,TIME_x_M_y_S(0,2)      ,0          	,0},
	{0,0,0,0,0}	
};
unsigned char code MENU7[][5] = {//西洋参粉
	{OB_Motor|End_Time   			,TIME_x_M_y_S(1,30)  	,MOTOR_MODE  	,L7},
	{0,0,0,0,0}	
};
unsigned char code MENU8[][5] = {//果蔬汁
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,25) 	,MOTOR_MODE 	,L8},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,35) 	,MOTOR_MODE 	,L2},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,25) 	,MOTOR_MODE 	,L10},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{OB_Motor|End_Time   			,TIME_x_M_y_S(0,23) 	,MOTOR_MODE 	,L9},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{0,0,0,0,0}		
};
unsigned char code MENU9[][5]={//奶昔
	{OB_Motor|End_Time				,TIME_x_M_y_S(1,5) 		,MOTOR_MODE 	,L5},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{0,0,0,0,0}																					
};
unsigned char code MENU10[][5]={//冰沙
	{OB_Motor|End_Time				,TIME_x_M_y_S(0,4) 		,MOTOR_MODE 	,L10},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,4)  	,0           	,0},
	{OB_Motor|End_Time				,TIME_x_M_y_S(0,2) 		,MOTOR_MODE 	,L2_0},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,4)  	,0           	,0},
	{OB_Repeat|End_Time        		,TIME_x_M_y_S(0,36)  	,2           	,1 },
	{OB_Motor|End_Time				,TIME_x_M_y_S(0,2) 		,MOTOR_MODE 	,L2_0},
	{OB_NULL|End_Time    			,TIME_x_M_y_S(0,2)  	,0           	,0},
	{0,0,0,0,0}																					
};
unsigned char code MENU11[][5]= {//清洗
	{OB_Motor|End_Time  			,TIME_x_M_y_S(0,50)		,MOTOR_MODE		,L10},
	{0,0,0,0,0}		
};