

	{OB_Heater|Time_OR_Temp,            TIME_x_M_y_S(20, 0),     HEAT_L1_0_0    ,75             },
	{OB_Heater|Time_OR_Temp,            TIME_x_M_y_S(20, 0),     HEAT_L0_9_0    ,83             },
	{OB_Heater|Time_OR_Fy,              TIME_x_M_y_S(4, 0),      HEAT_L0_5_0    ,0              },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 20),     0              ,DISP_UPDATE    },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 10),     MOTOR_MODE     ,L3             },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 20),     0              ,0              },
	{OB_Heater|End_Time,                TIME_x_M_y_S(2, 0),      HEAT_L0_2_0    ,0              },
	{OB_Heater|End_Time,                TIME_x_M_y_S(1, 30),     HEAT_L0_1_0    ,0              },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 20),     0              ,0              },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 40),     MOTOR_MODE     ,L1             },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 30),     MOTOR_MODE     ,L4             },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 10),     0              ,0              },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 10),     MOTOR_MODE     ,L1             },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 20),     MOTOR_MODE     ,L5             },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 10),     0              ,0              },
	{OB_Repeat|End_Time,                TIME_x_M_y_S(2, 40),     3              ,1              },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 10),     0              ,0              },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 25),     MOTOR_MODE     ,L1             },
	{OB_Motor|End_Time,                 TIME_x_M_y_S(0, 25),     MOTOR_MODE     ,L7             },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 20),     0              ,0              },
	{OB_Repeat|End_Time,                TIME_x_M_y_S(12, 50),    3              ,1              },
	{OB_H_30S_M_5S|End_Time,            TIME_x_M_y_S(1, 0),      HEAT_L0_2_0    ,30             },
	{OB_NULL|End_Time,                  TIME_x_M_y_S(0, 10),     0              ,0              },
	{OB_H_60S_M_5S|End_Time,            TIME_x_M_y_S(3, 0),      HEAT_L0_1_0    ,60             },
